/**
   @file pybind11/pybspline.cxx

   @brief Pybind11 multivariate B-splines

   @author Matthias Moller

   @copyright This file is part of the IgANet project

   This Source Code Form is subject to the terms of the Mozilla Public
   License, v. 2.0. If a copy of the MPL was not distributed with this
   file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <torch/extension.h>

#include <pyconfig.hpp>

#include <bspline.hpp>

namespace py = pybind11;

void init_bspline(py::module_ &m) {
  py::enum_<enum iganet::init>(m, "init")
    .value("zeros",    iganet::init::zeros)
    .value("ones",     iganet::init::ones)
    .value("linear",   iganet::init::linear)
    .value("random",   iganet::init::random)
    .value("greville", iganet::init::greville);

  py::enum_<iganet::deriv>(m, "deriv")
    .value("func",    iganet::deriv::func)
    
    .value("dx",      iganet::deriv::dx)
    .value("dx1",     iganet::deriv::dx1)
    .value("dx2",     iganet::deriv::dx2)
    .value("dx3",     iganet::deriv::dx3)
    .value("dx4",     iganet::deriv::dx4)
    
    .value("dy1",     iganet::deriv::dy1)
    .value("dy2",     iganet::deriv::dy2)
    .value("dy3",     iganet::deriv::dy3)
    .value("dy4",     iganet::deriv::dy4)
    
    .value("dz1",     iganet::deriv::dz1)
    .value("dz2",     iganet::deriv::dz2)
    .value("dz3",     iganet::deriv::dz3)
    .value("dz4",     iganet::deriv::dz4)
    
    .value("dt1",     iganet::deriv::dt1)
    .value("dt2",     iganet::deriv::dt2)
    .value("dt3",     iganet::deriv::dt3)
    .value("dt4",     iganet::deriv::dt4)
    
    .value("dxdy",    iganet::deriv::dxdy)
    .value("dx1dy1",  iganet::deriv::dx1dy1)
    .value("dx2dy1",  iganet::deriv::dx2dy1)
    .value("dx3dy1",  iganet::deriv::dx3dy1)
    .value("dx4dy1",  iganet::deriv::dx4dy1)
    .value("dx1dy2",  iganet::deriv::dx1dy2)
    .value("dx2dy2",  iganet::deriv::dx2dy2)
    .value("dx3dy2",  iganet::deriv::dx3dy2)
    .value("dx4dy2",  iganet::deriv::dx4dy2)
    .value("dx1dy3",  iganet::deriv::dx1dy3)
    .value("dx2dy3",  iganet::deriv::dx2dy3)
    .value("dx3dy3",  iganet::deriv::dx3dy3)
    .value("dx4dy3",  iganet::deriv::dx4dy3)
    .value("dx1dy4",  iganet::deriv::dx1dy4)
    .value("dx2dy4",  iganet::deriv::dx2dy4)
    .value("dx3dy4",  iganet::deriv::dx3dy4)
    .value("dx4dy4",  iganet::deriv::dx4dy4)
    
    .value("dx1dz1",  iganet::deriv::dx1dz1)
    .value("dx2dz1",  iganet::deriv::dx2dz1)
    .value("dx3dz1",  iganet::deriv::dx3dz1)
    .value("dx4dz1",  iganet::deriv::dx4dz1)
    .value("dx1dz2",  iganet::deriv::dx1dz2)
    .value("dx2dz2",  iganet::deriv::dx2dz2)
    .value("dx3dz2",  iganet::deriv::dx3dz2)
    .value("dx4dz2",  iganet::deriv::dx4dz2)
    .value("dx1dz3",  iganet::deriv::dx1dz3)
    .value("dx2dz3",  iganet::deriv::dx2dz3)
    .value("dx3dz3",  iganet::deriv::dx3dz3)
    .value("dx4dz3",  iganet::deriv::dx4dz3)
    .value("dx1dz4",  iganet::deriv::dx1dz4)
    .value("dx2dz4",  iganet::deriv::dx2dz4)
    .value("dx3dz4",  iganet::deriv::dx3dz4)
    .value("dx4dz4",  iganet::deriv::dx4dz4)

    .value("dx1dt1",  iganet::deriv::dx1dt1)
    .value("dx2dt1",  iganet::deriv::dx2dt1)
    .value("dx3dt1",  iganet::deriv::dx3dt1)
    .value("dx4dt1",  iganet::deriv::dx4dt1)
    .value("dx1dt2",  iganet::deriv::dx1dt2)
    .value("dx2dt2",  iganet::deriv::dx2dt2)
    .value("dx3dt2",  iganet::deriv::dx3dt2)
    .value("dx4dt2",  iganet::deriv::dx4dt2)
    .value("dx1dt3",  iganet::deriv::dx1dt3)
    .value("dx2dt3",  iganet::deriv::dx2dt3)
    .value("dx3dt3",  iganet::deriv::dx3dt3)
    .value("dx4dt3",  iganet::deriv::dx4dt3)
    .value("dx1dt4",  iganet::deriv::dx1dt4)
    .value("dx2dt4",  iganet::deriv::dx2dt4)
    .value("dx3dt4",  iganet::deriv::dx3dt4)
    .value("dx4dt4",  iganet::deriv::dx4dt4)

    .value("dydx",    iganet::deriv::dydx)
    .value("dy1dx1",  iganet::deriv::dy1dx1)
    .value("dy2dx1",  iganet::deriv::dy2dx1)
    .value("dy3dx1",  iganet::deriv::dy3dx1)
    .value("dy4dx1",  iganet::deriv::dy4dx1)
    .value("dy1dx2",  iganet::deriv::dy1dx2)
    .value("dy2dx2",  iganet::deriv::dy2dx2)
    .value("dy3dx2",  iganet::deriv::dy3dx2)
    .value("dy4dx2",  iganet::deriv::dy4dx2)
    .value("dy1dx3",  iganet::deriv::dy1dx3)
    .value("dy2dx3",  iganet::deriv::dy2dx3)
    .value("dy3dx3",  iganet::deriv::dy3dx3)
    .value("dy4dx3",  iganet::deriv::dy4dx3)
    .value("dy1dx4",  iganet::deriv::dy1dx4)
    .value("dy2dx4",  iganet::deriv::dy2dx4)
    .value("dy3dx4",  iganet::deriv::dy3dx4)
    .value("dy4dx4",  iganet::deriv::dy4dx4)

    .value("dydz",    iganet::deriv::dydz)
    .value("dy1dz1",  iganet::deriv::dy1dz1)
    .value("dy2dz1",  iganet::deriv::dy2dz1)
    .value("dy3dz1",  iganet::deriv::dy3dz1)
    .value("dy4dz1",  iganet::deriv::dy4dz1)
    .value("dy1dz2",  iganet::deriv::dy1dz2)
    .value("dy2dz2",  iganet::deriv::dy2dz2)
    .value("dy3dz2",  iganet::deriv::dy3dz2)
    .value("dy4dz2",  iganet::deriv::dy4dz2)
    .value("dy1dz3",  iganet::deriv::dy1dz3)
    .value("dy2dz3",  iganet::deriv::dy2dz3)
    .value("dy3dz3",  iganet::deriv::dy3dz3)
    .value("dy4dz3",  iganet::deriv::dy4dz3)
    .value("dy1dz4",  iganet::deriv::dy1dz4)
    .value("dy2dz4",  iganet::deriv::dy2dz4)
    .value("dy3dz4",  iganet::deriv::dy3dz4)
    .value("dy4dz4",  iganet::deriv::dy4dz4)

    .value("dydt",    iganet::deriv::dydt)
    .value("dy1dt1",  iganet::deriv::dy1dt1)
    .value("dy2dt1",  iganet::deriv::dy2dt1)
    .value("dy3dt1",  iganet::deriv::dy3dt1)
    .value("dy4dt1",  iganet::deriv::dy4dt1)
    .value("dy1dt2",  iganet::deriv::dy1dt2)
    .value("dy2dt2",  iganet::deriv::dy2dt2)
    .value("dy3dt2",  iganet::deriv::dy3dt2)
    .value("dy4dt2",  iganet::deriv::dy4dt2)
    .value("dy1dt3",  iganet::deriv::dy1dt3)
    .value("dy2dt3",  iganet::deriv::dy2dt3)
    .value("dy3dt3",  iganet::deriv::dy3dt3)
    .value("dy4dt3",  iganet::deriv::dy4dt3)
    .value("dy1dt4",  iganet::deriv::dy1dt4)
    .value("dy2dt4",  iganet::deriv::dy2dt4)
    .value("dy3dt4",  iganet::deriv::dy3dt4)
    .value("dy4dt4",  iganet::deriv::dy4dt4)

    .value("dzdx",    iganet::deriv::dzdx)
    .value("dz1dx1",  iganet::deriv::dz1dx1)
    .value("dz2dx1",  iganet::deriv::dz2dx1)
    .value("dz3dx1",  iganet::deriv::dz3dx1)
    .value("dz4dx1",  iganet::deriv::dz4dx1)
    .value("dz1dx2",  iganet::deriv::dz1dx2)
    .value("dz2dx2",  iganet::deriv::dz2dx2)
    .value("dz3dx2",  iganet::deriv::dz3dx2)
    .value("dz4dx2",  iganet::deriv::dz4dx2)
    .value("dz1dx3",  iganet::deriv::dz1dx3)
    .value("dz2dx3",  iganet::deriv::dz2dx3)
    .value("dz3dx3",  iganet::deriv::dz3dx3)
    .value("dz4dx3",  iganet::deriv::dz4dx3)
    .value("dz1dx4",  iganet::deriv::dz1dx4)
    .value("dz2dx4",  iganet::deriv::dz2dx4)
    .value("dz3dx4",  iganet::deriv::dz3dx4)
    .value("dz4dx4",  iganet::deriv::dz4dx4)

    .value("dzdy",    iganet::deriv::dzdy)
    .value("dz1dy1",  iganet::deriv::dz1dy1)
    .value("dz2dy1",  iganet::deriv::dz2dy1)
    .value("dz3dy1",  iganet::deriv::dz3dy1)
    .value("dz4dy1",  iganet::deriv::dz4dy1)
    .value("dz1dy2",  iganet::deriv::dz1dy2)
    .value("dz2dy2",  iganet::deriv::dz2dy2)
    .value("dz3dy2",  iganet::deriv::dz3dy2)
    .value("dz4dy2",  iganet::deriv::dz4dy2)
    .value("dz1dy3",  iganet::deriv::dz1dy3)
    .value("dz2dy3",  iganet::deriv::dz2dy3)
    .value("dz3dy3",  iganet::deriv::dz3dy3)
    .value("dz4dy3",  iganet::deriv::dz4dy3)
    .value("dz1dy4",  iganet::deriv::dz1dy4)
    .value("dz2dy4",  iganet::deriv::dz2dy4)
    .value("dz3dy4",  iganet::deriv::dz3dy4)
    .value("dz4dy4",  iganet::deriv::dz4dy4)

    .value("dzdt",    iganet::deriv::dzdt)
    .value("dz1dt1",  iganet::deriv::dz1dt1)
    .value("dz2dt1",  iganet::deriv::dz2dt1)
    .value("dz3dt1",  iganet::deriv::dz3dt1)
    .value("dz4dt1",  iganet::deriv::dz4dt1)
    .value("dz1dt2",  iganet::deriv::dz1dt2)
    .value("dz2dt2",  iganet::deriv::dz2dt2)
    .value("dz3dt2",  iganet::deriv::dz3dt2)
    .value("dz4dt2",  iganet::deriv::dz4dt2)
    .value("dz1dt3",  iganet::deriv::dz1dt3)
    .value("dz2dt3",  iganet::deriv::dz2dt3)
    .value("dz3dt3",  iganet::deriv::dz3dt3)
    .value("dz4dt3",  iganet::deriv::dz4dt3)
    .value("dz1dt4",  iganet::deriv::dz1dt4)
    .value("dz2dt4",  iganet::deriv::dz2dt4)
    .value("dz3dt4",  iganet::deriv::dz3dt4)
    .value("dz4dt4",  iganet::deriv::dz4dt4)

    .value("dtdx",    iganet::deriv::dtdx)
    .value("dt1dx1",  iganet::deriv::dt1dx1)
    .value("dt2dx1",  iganet::deriv::dt2dx1)
    .value("dt3dx1",  iganet::deriv::dt3dx1)
    .value("dt4dx1",  iganet::deriv::dt4dx1)
    .value("dt1dx2",  iganet::deriv::dt1dx2)
    .value("dt2dx2",  iganet::deriv::dt2dx2)
    .value("dt3dx2",  iganet::deriv::dt3dx2)
    .value("dt4dx2",  iganet::deriv::dt4dx2)
    .value("dt1dx3",  iganet::deriv::dt1dx3)
    .value("dt2dx3",  iganet::deriv::dt2dx3)
    .value("dt3dx3",  iganet::deriv::dt3dx3)
    .value("dt4dx3",  iganet::deriv::dt4dx3)
    .value("dt1dx4",  iganet::deriv::dt1dx4)
    .value("dt2dx4",  iganet::deriv::dt2dx4)
    .value("dt3dx4",  iganet::deriv::dt3dx4)
    .value("dt4dx4",  iganet::deriv::dt4dx4)

    .value("dtdy",    iganet::deriv::dtdy)
    .value("dt1dy1",  iganet::deriv::dt1dy1)
    .value("dt2dy1",  iganet::deriv::dt2dy1)
    .value("dt3dy1",  iganet::deriv::dt3dy1)
    .value("dt4dy1",  iganet::deriv::dt4dy1)
    .value("dt1dy2",  iganet::deriv::dt1dy2)
    .value("dt2dy2",  iganet::deriv::dt2dy2)
    .value("dt3dy2",  iganet::deriv::dt3dy2)
    .value("dt4dy2",  iganet::deriv::dt4dy2)
    .value("dt1dy3",  iganet::deriv::dt1dy3)
    .value("dt2dy3",  iganet::deriv::dt2dy3)
    .value("dt3dy3",  iganet::deriv::dt3dy3)
    .value("dt4dy3",  iganet::deriv::dt4dy3)
    .value("dt1dy4",  iganet::deriv::dt1dy4)
    .value("dt2dy4",  iganet::deriv::dt2dy4)
    .value("dt3dy4",  iganet::deriv::dt3dy4)
    .value("dt4dy4",  iganet::deriv::dt4dy4)

    .value("dtdz",    iganet::deriv::dtdz)
    .value("dt1dz1",  iganet::deriv::dt1dz1)
    .value("dt2dz1",  iganet::deriv::dt2dz1)
    .value("dt3dz1",  iganet::deriv::dt3dz1)
    .value("dt4dz1",  iganet::deriv::dt4dz1)
    .value("dt1dz2",  iganet::deriv::dt1dz2)
    .value("dt2dz2",  iganet::deriv::dt2dz2)
    .value("dt3dz2",  iganet::deriv::dt3dz2)
    .value("dt4dz2",  iganet::deriv::dt4dz2)
    .value("dt1dz3",  iganet::deriv::dt1dz3)
    .value("dt2dz3",  iganet::deriv::dt2dz3)
    .value("dt3dz3",  iganet::deriv::dt3dz3)
    .value("dt4dz3",  iganet::deriv::dt4dz3)
    .value("dt1dz4",  iganet::deriv::dt1dz4)
    .value("dt2dz4",  iganet::deriv::dt2dz4)
    .value("dt3dz4",  iganet::deriv::dt3dz4)
    .value("dt4dz4",  iganet::deriv::dt4dz4);
}
